name: y-an / sample-blog
baseurl: /sample-blog
markdown: kramdown
repository: <USERNAME>/<PROJECT>
permalink: /:year/:month/:day/:title

defaults:
  -
    scope:
      path: "" 
      type: "posts" 
    values:
      layout: "post"